# Generated by Django 4.2.1 on 2023-06-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_view_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='View_Order',
        ),
    ]
